#ifndef __PORT_H__
#define __PORT_H__

#include "Main.h"

/* Leds' pins */
#define LED_1_PORT_DR   (GPIO_PORT3_DATA)
#define LED_1_PORT_CR   (GPIO_PORT3_DIRECTION)
#define LED_1_PIN       (GPIO_PIN_7)

#define LED_2_PORT_DR   (GPIO_PORT3_DATA)
#define LED_2_PORT_CR   (GPIO_PORT3_DIRECTION)
#define LED_2_PIN       (GPIO_PIN_6)

#define BUZZER_PORT_DR (GPIO_PORT3_DATA)
#define BUZZER_PORT_CR (GPIO_PORT3_DIRECTION)
#define BUZZER_PIN       (GPIO_PIN_2)

#define OPEN_PORT_DR (GPIO_PORT3_DATA)
#define OPEN_PORT_CR (GPIO_PORT3_DIRECTION)
#define OPEN_PIN       (GPIO_PIN_3)


#define MOTOR_PORT_DR (GPIO_PORT2_DATA)
#define MOTOR_PORT_CR (GPIO_PORT2_DIRECTION)
#define MOTOR_PIN       (GPIO_PIN_0)

#define SWITCH_4DOWN_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_4DOWN_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_4DOWN_PIN       (GPIO_PIN_0)

#define SWITCH_3UP_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_3UP_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_3UP_PIN       (GPIO_PIN_1)

#define SWITCH_3DOWN_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_3DOWN_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_3DOWN_PIN       (GPIO_PIN_2)

#define SWITCH_2UP_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_2UP_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_2UP_PIN       (GPIO_PIN_3)

#define SWITCH_2DOWN_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_2DOWN_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_2DOWN_PIN       (GPIO_PIN_4)

#define SWITCH_1UP_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_1UP_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_1UP_PIN       (GPIO_PIN_5)

#define SWITCH_1DOWN_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_1DOWN_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_1DOWN_PIN       (GPIO_PIN_6)

#define SWITCH_G_UP_PORT_DR (GPIO_PORT0_DATA)
#define SWITCH_G_UP_PORT_CR (GPIO_PORT0_DIRECTION)
#define SWITCH_G_UP_PIN       (GPIO_PIN_7)

#define SWITCH_4_PORT_DR (GPIO_PORT2_DATA)
#define SWITCH_4_PORT_CR (GPIO_PORT2_DIRECTION)
#define SWITCH_4_PIN       (GPIO_PIN_1)

#define SWITCH_3_PORT_DR (GPIO_PORT2_DATA)
#define SWITCH_3_PORT_CR (GPIO_PORT2_DIRECTION)
#define SWITCH_3_PIN       (GPIO_PIN_2)

#define SWITCH_2_PORT_DR (GPIO_PORT2_DATA)
#define SWITCH_2_PORT_CR (GPIO_PORT2_DIRECTION)
#define SWITCH_2_PIN       (GPIO_PIN_3)

#define SWITCH_1_PORT_DR (GPIO_PORT2_DATA)
#define SWITCH_1_PORT_CR (GPIO_PORT2_DIRECTION)
#define SWITCH_1_PIN       (GPIO_PIN_4)

#define SWITCH_G_PORT_DR (GPIO_PORT2_DATA)
#define SWITCH_G_PORT_CR (GPIO_PORT2_DIRECTION)
#define SWITCH_G_PIN       (GPIO_PIN_5)


/* End of code filling */
#endif // __PORT_H__
